/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/1.jpg > opt-moz-base/1-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/2.jpg > opt-moz-base/2-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/3.jpg > opt-moz-base/3-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/4.jpg > opt-moz-base/4-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/5.jpg > opt-moz-base/5-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/6.jpg > opt-moz-base/6-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/7.jpg > opt-moz-base/7-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/8.jpg > opt-moz-base/8-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/9.jpg > opt-moz-base/9-moz-base.jpg
/usr/local/opt/mozjpeg/bin/jpegtran -revert -copy none -optimize source/10.jpg > opt-moz-base/10-moz-base.jpg
